### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by danextpope** [Atlantis-PBEM/Atlantis#10]
While perusing the source code I came across the following

`ARegion::TownHabitat()`, economy.cpp, lines 1090 and 1094

In both cases, an `ItemType::flags` value is compared to `IT_` value (`IT_FOOD` and `IT_MOUNT` respectively).  Elsewhere it's `ItemType::type` that's compared to these values.

As far as I can tell, the maximum value for `flags` is `0x3F`, which means these two tests will never be true.

**Comment by jt-traub** [comment]
Definite bug.  Fixed.  The .flags field should have been the .type field in those comparisons.
While the initial analysis was correct in that this function isn't called except during setup today, there is no theoretical reason a town couldn't grow up during the game if code to allow that was written and this would fail in that hypothetical instance.
This has been changes (in PR#193) to fix the bug so it's comparing on the correct field.
