### ISSUE TITLE
Rules do not specify that livestock and/or magical items cannot be transported via quartermasters.

### ISSUE THREAD

**Issue by Elfinhope** [Atlantis-PBEM/Atlantis#107]
Transportation of livestock and magical items are not allowed via quartermaster units but must be carried from one location to another by a unit.

**Comment by rmstdope** [comment]
I am looking to contribute somewhat to the Atlantis development and thought this would be a good initial PR to fix. Mind of I take this one? Easy enough to start getting me familiar with the code again.
