### ISSUE TITLE
special items check in parseorders.cpp

### ISSUE THREAD

**Issue by ennorehling** [Atlantis-PBEM/Atlantis#11]
In line 1027, we have this code:
    if (bt == NULL || !bt->flags & BattleItemType::SPECIAL) {

it looks like there should be parentheses here because !bt->flags will otherwise be promoted to boolean, and binary-and with a boolean makes no sense. I suggest:
    if (bt == NULL || !(bt->flags & BattleItemType::SPECIAL)) {

Do you want a pull requests?

**Comment by Loriaki** [comment]
Ich kann das auch so einspielen.
Danke

**Comment by Loriaki** [comment]
Thanks for the fix.

**Comment by Loriaki** [comment]
close
