### ISSUE TITLE
standard game profile does not build

### ISSUE THREAD

**Issue by Loriaki** [Atlantis-PBEM/Atlantis#14]
standard/extra.cpp: In member function 'Faction\* Game::CheckVictory()':
standard/extra.cpp:107:4: error: 'reg' was not declared in this scope

**Comment by Loriaki** [comment]
It seems the wrong variable name has been used while iterating over regions.

**Comment by Loriaki** [comment]
close

**Comment by jt-traub** [comment]
This has long been fixed, closing.
