### ISSUE TITLE
Game::ModifyAttribMod array index error?

### ISSUE THREAD

**Issue by ennorehling** [Atlantis-PBEM/Atlantis#18]
In Game::ModifyAttribMod there is a check to make sure index is in [0,5]:

```
if (index < 0 || index > 5) return;
```

However, a few lines down, we access `mp->mods[index]`, although mods is an array of size 5 (see skills.h). That means when index==5, this is going to be an out-of-bounds access.

I don't know where the magic number 5 comes from, and whether the correct fix is to change the array size, but there is at least one call in the code that explicitly uses an index of 5, in extra.cpp line 255:

```
    ModifyAttribMod("stealth", 5, AttribModItem::SKILL,"INVI", AttribModItem::UNIT_LEVEL_HALF, 1); //make sure 6 slots available - default version has only 5.
```

That comment seems to imply that the author knew about the problem? I'm confused.

**Comment by jt-traub** [comment]
Included in https://github.com/Atlantis-PBEM/Atlantis/pull/193
