### ISSUE TITLE
Game::ModifySpecialDamage out-of-bound array index?

### ISSUE THREAD

**Issue by ennorehling** [Atlantis-PBEM/Atlantis#19]
see issue #18 for a similar problem. In this function, `index` is tested to be in [0,4] with

```
if (index < 0 || index > 4) return;
```

but then if it is 4, the later line will access the sp->damage array out of bounds, because it has only 4 elements:

```
    sp->damage[index].type = type;
```

It looks like the only times this is called from existing code is with index 0 or 1, though, so this probably does not happen in play right now? Still is bad code, imho.

**Comment by jt-traub** [comment]
Included in https://github.com/Atlantis-PBEM/Atlantis/pull/193
