### ISSUE TITLE
array index error in Game::DoBuy

### ISSUE THREAD

**Issue by ennorehling** [Atlantis-PBEM/Atlantis#21]
I believe that the loop in line 1696 of runorders.cpp is not calculating the array bounds correctly:

```
1696                                                                for (int ms = 0; ms < ((int) sizeof(mt->skills))/((int) sizeof(int)); ms++)
```

mt->skills is not an array of integers, but of `char const *` (see items.h), which means that each array entry is 8 bytes wide, not 4, and the loop iterates over 12 entries, when Mantype.skills has only 6.

I would suggest replacing this term with sizeof(mt->skills)/sizeof(mt->skills[0]).

**Comment by danextpope** [comment]
Probably due to this code dating back to pointers being 4 bytes.  There are, unfortunately, many unsafe assumptions like this.

**Comment by ennorehling** [comment]
I guess so, but we cannot keep running Atlantis on a Raspberry Pi, and there are very few other computers that are not 64 bit today.

**Comment by danextpope** [comment]
Agreed.  Unfortunately, a full code review is a rather large project.

**Comment by ennorehling** [comment]
True. On the one hand, there are only 85 KLOC, but on the other, almost none of those are comments and even fewer are tests, so it's often impossible to know what the author intended when they wrote the code. I can tell that it's wrong, but not how to fix it.

**Comment by Loriaki** [comment]
On Wed, Nov 18, 2015 at 06:00:20AM -0800, Ari D Jordon wrote:
> Agreed.  Unfortunately, a full code review is a rather large project.

Indeed .. if you try to start, you have to keep on for sometime to
have it working again :)
(Perhaps we should create a branch for that ?)

Loria

**Comment by danextpope** [comment]
> Indeed .. if you try to start, you have to keep on for sometime to
> have it working again :)
> (Perhaps we should create a branch for that ?)

Quite a bit.  Especially if you actually tried to get it up to date
with C++11.  A while back I started a project to port it to C#, which
made me realize just what a Charlie Foxtrot the source is :/

**Comment by Loriaki** [comment]
On Wed, Nov 18, 2015 at 06:35:39AM -0800, Ari D Jordon wrote:
> > Indeed .. if you try to start, you have to keep on for sometime to
> > have it working again :)
> > (Perhaps we should create a branch for that ?)
> 
> Quite a bit.  Especially if you actually tried to get it up to date
> with C++11.  A while back I started a project to port it to C#, which
> made me realize just what a Charlie Foxtrot the source is :/

Well it would be even a hazzle to get clean C++ to C# but since 
Atlantis is far from being clean C++ .
It looks like is has been C and was moved to use features of C++
but never reaced C++ ...

I once started to try this ... took a deep breath started to try to
keep it compiling and got distracted by something else :/

If you like, we could again try to push it :-)

Loria

**Comment by sgb** [comment]
>
> Indeed .. if you try to start, you have to keep on for sometime to
> have it working again :)
> (Perhaps we should create a branch for that ?)
>

I note that one of the previous "fixes" happened to cause the code to no
longer even compile, which makes me rather nervous about the rest of them.
Are you testing them before putting in these change requests?

Steve.

**Comment by sgb** [comment]
On 19 November 2015 at 00:54, Enno Rehling <notifications@github.com> wrote:

> I guess so, but we cannot keep running Atlantis on a Raspberry Pi, and
> there are very few other computers that are not 64 bit today.
>
Atlantis runs fine on 64 bit systems - the Havilah game is all 64 bit
hosted, and has been running very stably there.

One of the issues with Atlantis being an open-source project is that there
are lots of optional components, some of which are poorly designed and
maintained.  The core, however, is quite robust.

Steve.

**Comment by Loriaki** [comment]
Hi,

the current set (#14) of code does compile:
 make standard                                                                    ~/Atlantis/Atlantis-github
make GAME=standard
make[1]: Entering directory `/usr/home/beacon/loria/Atlantis/Atlantis-github'
if [ ! -d obj ]; then mkdir obj; fi
if [ ! -d standard/obj ]; then mkdir standard/obj; fi
g++ -g -I. -I.. -Wall -c -o standard/obj/extra.o standard/extra.cpp
.
.
.
g++ -g -I. -I.. -Wall -c -o obj/template.o template.cpp
g++ -g -I. -I.. -Wall -c -o obj/unit.o unit.cpp
g++ -g -I. -I.. -Wall -o standard/standard standard/obj/extra.o standard/obj/map.o standard/obj/monsters.o standard/obj/rules.o standard/obj/world.o obj/alist.o obj/aregion.o obj/army.o obj/astring.o obj/battle.o obj/economy.o obj/edit.o obj/faction.o obj/fileio.o obj/game.o obj/gamedata.o obj/gamedefs.o obj/gameio.o obj/genrules.o obj/i_rand.o obj/items.o obj/main.o obj/market.o obj/modify.o obj/monthorders.o obj/npc.o obj/object.o obj/orders.o obj/parseorders.o obj/production.o obj/quests.o obj/runorders.o obj/shields.o obj/skills.o obj/skillshows.o obj/specials.o obj/spells.o obj/template.o obj/unit.o

I havent checked it running … but there are plans for a testrun :)

**Comment by ennorehling** [comment]
compiling is step one. not all code that compiles is correct, or this job would be easy.

**Comment by sgb** [comment]
>
> compiling is step one. not all code that compiles is correct, or this job
> would be easy.
>
Which is why the fact that one of the recent "patches" did not compile (and
Loriaki had to fix it) makes me so nervous.  Not all code that compiles is
correct, but code that does not compile is definitely not correct, and
shows that you hadn't even done step one.

As someone who is using this code base, having changes that have not been
tested committed to the repository makes me nervous.

Steve.

**Comment by ennorehling** [comment]
That was my bad, I didn't compile my pull request. Having a CI build would be a good improvement (https://travis-ci.org is free and works great for Eressea).

**Comment by jt-traub** [comment]
I went through and audited all instances of `sizeof(<array>) / sizeof(<type>)` and made sure that the type in the second one was actually the first element of the array (ie: ` sizeof(<static array>) / sizeof(<static array>[0])` ).  This change will go in as part of PR #193
