### ISSUE TITLE
memory leak in Game::Do1Assassinate

### ISSUE THREAD

**Issue by ennorehling** [Atlantis-PBEM/Atlantis#22]
The variable `seers` is allocated in this call to CanSeeSteal (new AList) in line 322:

```
AList *seers = CanSeeSteal(r, u);
```

This list is never deleted anywhere later in the function, which has multiple return paths (I believe this is the kind of thing std::auto_ptr<> is good for).

**Comment by jt-traub** [comment]
This, being a memory leak, is going to be fixed.  Fixing in upcoming PR #193
