### ISSUE TITLE
GUARD doesn't unset when skill is diluted

### ISSUE THREAD

**Issue by artyomtrityak** [Atlantis-PBEM/Atlantis#33]
10 men with COMB 1 (30) are guarding. They buy 1 more man, now have COMB 0 (27) and are still guarding. They should not be.

Ref: https://github.com/artyomtrityak/Atlantis/issues/21

**Comment by sgb** [comment]
They will not be next time guard orders run.

You could say that at the time they set up the guard they had guys who knew how to fight, and those guys are still in the unit.  It's a consequence of the phased nature of turns.  I don't think it needs fixing :-)

**Comment by artyomtrityak** [comment]
Ok :)
