### ISSUE TITLE
GUARD unsets and then sets if player command GUARD 1 on guarding unit

### ISSUE THREAD

**Issue by artyomtrityak** [Atlantis-PBEM/Atlantis#34]
GUARD is unsets and then sets if player command GUARD 1 on guarding unit. So it is possible that another players will set guard at the same time.

**Comment by artyomtrityak** [comment]
Ref: https://github.com/artyomtrityak/Atlantis/issues/27

**Comment by sgb** [comment]
In parseorder.cpp:2579 there is a check for this.  Are you sure this happens?

But other players SHOULD be able to set guard while a unit is guarding, so maybe the test wasn't testing what you thought it was?

**Comment by artyomtrityak** [comment]
Yes, i thought other faction can not set guard if someone already guarding region. In this case it is not a bug.
