### ISSUE TITLE
Future of atlantis-pbem.org domain

### ISSUE THREAD

**Issue by ChristopherA** [Atlantis-PBEM/Atlantis#9]
I hold the atlantis-pbem.org domain (and a moderator of the user group), from back when I was trying to herd some cats for a new release. I am no longer active in atlantis.

Is there someone that wishes to make active use of the domain? Maybe a better website? Maybe point it to this GitHub repository?

Free to whomever has the best proposal. Contact me at ChristopherA@RPG.net.

-- Christopher Allen
   Owner, Publisher — RPG.net

**Comment by Loriaki** [comment]
I did send you some mails about this. I will retry.

**Comment by ChristopherA** [comment]
I am looking for a concrete proposal, or even a draft website.

**Comment by jt-traub** [comment]
This is a long-dead issue as Artem now holds that domain.
